"""Add Review Model

Revision ID: bbc964e9448e
Revises: 36ef08fe3d37
Create Date: 2026-01-18 15:12:25.233833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbc964e9448e'
down_revision = '36ef08fe3d37'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
